import os
import time


def batch_run_distributed(cmd_list, order=1):
    for i in cmd_list[::order]:
        try:
            i = "torchrun --nproc_per_node 1 --master_port 29528 run_cl.py " + i
            os.system(i)
            time.sleep(10)
            print(i)
        except Exception as e:
            print(e)
            print(i, "failed")


def batch_run_interactive(cmd_list, order=1):
    for i in cmd_list[::order]:
        print(i)
    for i in cmd_list[::order]:
        try:
            i = "python run_cl.py " + i
            os.system(i)
            time.sleep(10)
            print(i)
        except:
            print(i, " failed!")


if __name__ == "__main__":
    cmd_standard_cl_benchmark_order1 = [
        "--name shlpt_scl1_42 --dataset scl_seq1 --task_set dataset_stream --model_set t5-large-lr0.3-256 --train_set train_offline_8_bsz --algo shlpt --load_algo_args --scenario til --epoch 50 --task_num 4 --pri_task shlpt --gradient_accumulation_steps 1 --prompt_number 150 --loss_every 10 --seed 42 --n_gpu 1 --split_train_file_to_valid --k_train 75 --k_val 75 --k_test 100 --gpu_id 7 --softmax_temperature 20000 --estimator attention --threshold 0.06 --add_asc_loss_filtered --asc_temperature 1 --asc_lamb 0.5 --add_hsc_loss --hsc_temperature 1 --hsc_lamb 0.1 --accum_epoch 35",
        "--name shlpt_scl1_142 --dataset scl_seq1 --task_set dataset_stream --model_set t5-large-lr0.3-256 --train_set train_offline_8_bsz --algo shlpt --load_algo_args --scenario til --epoch 50 --task_num 4 --pri_task shlpt --gradient_accumulation_steps 1 --prompt_number 150 --loss_every 10 --seed 142 --n_gpu 1 --split_train_file_to_valid --k_train 75 --k_val 75 --k_test 100 --gpu_id 7 --softmax_temperature 20000 --estimator attention --threshold 0.06 --add_asc_loss_filtered --asc_temperature 1 --asc_lamb 0.5 --add_hsc_loss --hsc_temperature 1 --hsc_lamb 0.1 --accum_epoch 35",
        "--name shlpt_scl1_242 --dataset scl_seq1 --task_set dataset_stream --model_set t5-large-lr0.3-256 --train_set train_offline_8_bsz --algo shlpt --load_algo_args --scenario til --epoch 50 --task_num 4 --pri_task shlpt --gradient_accumulation_steps 1 --prompt_number 150 --loss_every 10 --seed 242 --n_gpu 1 --split_train_file_to_valid --k_train 75 --k_val 75 --k_test 100 --gpu_id 7 --softmax_temperature 20000 --estimator attention --threshold 0.06 --add_asc_loss_filtered --asc_temperature 1 --asc_lamb 0.5 --add_hsc_loss --hsc_temperature 1 --hsc_lamb 0.1 --accum_epoch 35",
    ]
    cmd_standard_cl_benchmark_order2 = [
        "--name shlpt_scl1_42 --dataset scl_seq2 --task_set dataset_stream --model_set t5-large-lr0.3-256 --train_set train_offline_8_bsz --algo shlpt --load_algo_args --scenario til --epoch 50 --task_num 4 --pri_task shlpt --gradient_accumulation_steps 1 --prompt_number 150 --loss_every 10 --seed 42 --n_gpu 1 --split_train_file_to_valid --k_train 75 --k_val 75 --k_test 100 --gpu_id 7 --softmax_temperature 20000 --estimator attention --threshold 0.06 --add_asc_loss_filtered --asc_temperature 1 --asc_lamb 0.5 --add_hsc_loss --hsc_temperature 1 --hsc_lamb 0.1 --accum_epoch 35",
        "--name shlpt_scl1_142 --dataset scl_seq2 --task_set dataset_stream --model_set t5-large-lr0.3-256 --train_set train_offline_8_bsz --algo shlpt --load_algo_args --scenario til --epoch 50 --task_num 4 --pri_task shlpt --gradient_accumulation_steps 1 --prompt_number 150 --loss_every 10 --seed 142 --n_gpu 1 --split_train_file_to_valid --k_train 75 --k_val 75 --k_test 100 --gpu_id 7 --softmax_temperature 20000 --estimator attention --threshold 0.06 --add_asc_loss_filtered --asc_temperature 1 --asc_lamb 0.5 --add_hsc_loss --hsc_temperature 1 --hsc_lamb 0.1 --accum_epoch 35",
        "--name shlpt_scl1_242 --dataset scl_seq2 --task_set dataset_stream --model_set t5-large-lr0.3-256 --train_set train_offline_8_bsz --algo shlpt --load_algo_args --scenario til --epoch 50 --task_num 4 --pri_task shlpt --gradient_accumulation_steps 1 --prompt_number 150 --loss_every 10 --seed 242 --n_gpu 1 --split_train_file_to_valid --k_train 75 --k_val 75 --k_test 100 --gpu_id 7 --softmax_temperature 20000 --estimator attention --threshold 0.06 --add_asc_loss_filtered --asc_temperature 1 --asc_lamb 0.5 --add_hsc_loss --hsc_temperature 1 --hsc_lamb 0.1 --accum_epoch 35",
    ]
    cmd_standard_cl_benchmark_order3 = [
        "--name shlpt_scl3_42 --dataset scl_seq3 --task_set dataset_stream --model_set t5-large-lr0.3-256 --train_set train_offline_8_bsz --algo shlpt --load_algo_args --scenario til --epoch 50 --task_num 4 --pri_task shlpt --gradient_accumulation_steps 1 --prompt_number 150 --loss_every 10 --seed 42 --n_gpu 1 --split_train_file_to_valid --k_train 75 --k_val 75 --k_test 100 --gpu_id 7 --softmax_temperature 20000 --estimator attention --threshold 0.06 --add_asc_loss_filtered --asc_temperature 1 --asc_lamb 0.5 --add_hsc_loss --hsc_temperature 1 --hsc_lamb 0.1 --accum_epoch 35",
        "--name shlpt_scl3_142 --dataset scl_seq3 --task_set dataset_stream --model_set t5-large-lr0.3-256 --train_set train_offline_8_bsz --algo shlpt --load_algo_args --scenario til --epoch 50 --task_num 4 --pri_task shlpt --gradient_accumulation_steps 1 --prompt_number 150 --loss_every 10 --seed 142 --n_gpu 1 --split_train_file_to_valid --k_train 75 --k_val 75 --k_test 100 --gpu_id 7 --softmax_temperature 20000 --estimator attention --threshold 0.06 --add_asc_loss_filtered --asc_temperature 1 --asc_lamb 0.5 --add_hsc_loss --hsc_temperature 1 --hsc_lamb 0.1 --accum_epoch 35",
        "--name shlpt_scl3_242 --dataset scl_seq3 --task_set dataset_stream --model_set t5-large-lr0.3-256 --train_set train_offline_8_bsz --algo shlpt --load_algo_args --scenario til --epoch 50 --task_num 4 --pri_task shlpt --gradient_accumulation_steps 1 --prompt_number 150 --loss_every 10 --seed 242 --n_gpu 1 --split_train_file_to_valid --k_train 75 --k_val 75 --k_test 100 --gpu_id 7 --softmax_temperature 20000 --estimator attention --threshold 0.06 --add_asc_loss_filtered --asc_temperature 1 --asc_lamb 0.5 --add_hsc_loss --hsc_temperature 1 --hsc_lamb 0.1 --accum_epoch 35",
    ]
    cmd_large_number_of_tasks_order1 = [
        "--name shlpt_long1_42 --dataset long_seq1 --task_set dataset_stream --model_set t5-large-lr0.3-256 --train_set train_offline_8_bsz --algo shlpt --load_algo_args --scenario til --epoch 80 --task_num 15 --pri_task shlpt --gradient_accumulation_steps 1 --prompt_number 150 --loss_every 10 --seed 42 --n_gpu 1 --split_train_file_to_valid --k_train 75 --k_val 75 --k_test 100 --gpu_id 6 --softmax_temperature 20000 --estimator attention --threshold 0.06 --add_asc_loss_filtered --asc_temperature 1 --asc_lamb 0.5 --add_hsc_loss --hsc_temperature 1 --hsc_lamb 0.1 --accum_epoch 50",
        "--name shlpt_long1_142 --dataset long_seq1 --task_set dataset_stream --model_set t5-large-lr0.3-256 --train_set train_offline_8_bsz --algo shlpt --load_algo_args --scenario til --epoch 80 --task_num 15 --pri_task shlpt --gradient_accumulation_steps 1 --prompt_number 150 --loss_every 10 --seed 142 --n_gpu 1 --split_train_file_to_valid --k_train 75 --k_val 75 --k_test 100 --gpu_id 7 --softmax_temperature 20000 --estimator attention --threshold 0.06 --add_asc_loss_filtered --asc_temperature 1 --asc_lamb 0.5 --add_hsc_loss --hsc_temperature 1 --hsc_lamb 0.1 --accum_epoch 50",
        "--name shlpt_long1_242 --dataset long_seq1 --task_set dataset_stream --model_set t5-large-lr0.3-256 --train_set train_offline_8_bsz --algo shlpt --load_algo_args --scenario til --epoch 80 --task_num 15 --pri_task shlpt --gradient_accumulation_steps 1 --prompt_number 150 --loss_every 10 --seed 242 --n_gpu 1 --split_train_file_to_valid --k_train 75 --k_val 75 --k_test 100 --gpu_id 7 --softmax_temperature 20000 --estimator attention --threshold 0.06 --add_asc_loss_filtered --asc_temperature 1 --asc_lamb 0.5 --add_hsc_loss --hsc_temperature 1 --hsc_lamb 0.1 --accum_epoch 50",
    ]
    cmd_large_number_of_tasks_order2 = [
        "--name shlpt_long2_42 --dataset long_seq2 --task_set dataset_stream --model_set t5-large-lr0.3-256 --train_set train_offline_8_bsz --algo shlpt --load_algo_args --scenario til --epoch 80 --task_num 15 --pri_task shlpt --gradient_accumulation_steps 1 --prompt_number 150 --loss_every 10 --seed 42 --n_gpu 1 --split_train_file_to_valid --k_train 75 --k_val 75 --k_test 100 --gpu_id 7 --softmax_temperature 20000 --estimator attention --threshold 0.06 --add_asc_loss_filtered --asc_temperature 1 --asc_lamb 0.5 --add_hsc_loss --hsc_temperature 1 --hsc_lamb 0.1 --accum_epoch 50",
        "--name shlpt_long2_142 --dataset long_seq2 --task_set dataset_stream --model_set t5-large-lr0.3-256 --train_set train_offline_8_bsz --algo shlpt --load_algo_args --scenario til --epoch 80 --task_num 15 --pri_task shlpt --gradient_accumulation_steps 1 --prompt_number 150 --loss_every 10 --seed 142 --n_gpu 1 --split_train_file_to_valid --k_train 75 --k_val 75 --k_test 100 --gpu_id 7 --softmax_temperature 20000 --estimator attention --threshold 0.06 --add_asc_loss_filtered --asc_temperature 1 --asc_lamb 0.5 --add_hsc_loss --hsc_temperature 1 --hsc_lamb 0.1 --accum_epoch 50",
        "--name shlpt_long2_242 --dataset long_seq2 --task_set dataset_stream --model_set t5-large-lr0.3-256 --train_set train_offline_8_bsz --algo shlpt --load_algo_args --scenario til --epoch 80 --task_num 15 --pri_task shlpt --gradient_accumulation_steps 1 --prompt_number 150 --loss_every 10 --seed 242 --n_gpu 1 --split_train_file_to_valid --k_train 75 --k_val 75 --k_test 100 --gpu_id 7 --softmax_temperature 20000 --estimator attention --threshold 0.06 --add_asc_loss_filtered --asc_temperature 1 --asc_lamb 0.5 --add_hsc_loss --hsc_temperature 1 --hsc_lamb 0.1 --accum_epoch 50",
    ]
    cmd_large_number_of_tasks_order3 = [
        "--name shlpt_long3_42 --dataset long_seq3 --task_set dataset_stream --model_set t5-large-lr0.3-256 --train_set train_offline_8_bsz --algo shlpt --load_algo_args --scenario til --epoch 80 --task_num 15 --pri_task shlpt --gradient_accumulation_steps 1 --prompt_number 150 --loss_every 10 --seed 42 --n_gpu 1 --split_train_file_to_valid --k_train 75 --k_val 75 --k_test 100 --gpu_id 7 --softmax_temperature 20000 --estimator attention --threshold 0.06 --add_asc_loss_filtered --asc_temperature 1 --asc_lamb 0.5 --add_hsc_loss --hsc_temperature 1 --hsc_lamb 0.1 --accum_epoch 50",
        "--name shlpt_long3_142 --dataset long_seq3 --task_set dataset_stream --model_set t5-large-lr0.3-256 --train_set train_offline_8_bsz --algo shlpt --load_algo_args --scenario til --epoch 80 --task_num 15 --pri_task shlpt --gradient_accumulation_steps 1 --prompt_number 150 --loss_every 10 --seed 142 --n_gpu 1 --split_train_file_to_valid --k_train 75 --k_val 75 --k_test 100 --gpu_id 7 --softmax_temperature 20000 --estimator attention --threshold 0.06 --add_asc_loss_filtered --asc_temperature 1 --asc_lamb 0.5 --add_hsc_loss --hsc_temperature 1 --hsc_lamb 0.1 --accum_epoch 50",
        "--name shlpt_long3_242 --dataset long_seq3 --task_set dataset_stream --model_set t5-large-lr0.3-256 --train_set train_offline_8_bsz --algo shlpt --load_algo_args --scenario til --epoch 80 --task_num 15 --pri_task shlpt --gradient_accumulation_steps 1 --prompt_number 150 --loss_every 10 --seed 242 --n_gpu 1 --split_train_file_to_valid --k_train 75 --k_val 75 --k_test 100 --gpu_id 7 --softmax_temperature 20000 --estimator attention --threshold 0.06 --add_asc_loss_filtered --asc_temperature 1 --asc_lamb 0.5 --add_hsc_loss --hsc_temperature 1 --hsc_lamb 0.1 --accum_epoch 50",
    ]
    cmd_negative_transfer_order1 = [
        "--name shlpt_dis1_42 --dataset dis_seq1 --task_set dataset_stream --model_set t5-large-lr0.3-256 --train_set train_offline_8_bsz --algo shlpt --load_algo_args --scenario til --epoch 50 --task_num 5 --pri_task shlpt --gradient_accumulation_steps 1 --prompt_number 150 --loss_every 10 --seed 42 --n_gpu 1 --split_train_file_to_valid --k_train 75 --k_val 75 --k_test 100 --gpu_id 5 --softmax_temperature 20000 --estimator attention --threshold 1.5 --all_dissimilar --add_asc_loss_filtered --asc_temperature 1 --asc_lamb 0.5 --add_hsc_loss --hsc_temperature 1 --hsc_lamb 0.1 --accum_epoch 35",
        "--name shlpt_dis1_142 --dataset dis_seq1 --task_set dataset_stream --model_set t5-large-lr0.3-256 --train_set train_offline_8_bsz --algo shlpt --load_algo_args --scenario til --epoch 50 --task_num 5 --pri_task shlpt --gradient_accumulation_steps 1 --prompt_number 150 --loss_every 10 --seed 142 --n_gpu 1 --split_train_file_to_valid --k_train 75 --k_val 75 --k_test 100 --gpu_id 5 --softmax_temperature 20000 --estimator attention --threshold 1.5 --all_dissimilar --add_asc_loss_filtered --asc_temperature 1 --asc_lamb 0.5 --add_hsc_loss --hsc_temperature 1 --hsc_lamb 0.1 --accum_epoch 35",
        "--name shlpt_dis1_242 --dataset dis_seq1 --task_set dataset_stream --model_set t5-large-lr0.3-256 --train_set train_offline_8_bsz --algo shlpt --load_algo_args --scenario til --epoch 50 --task_num 5 --pri_task shlpt --gradient_accumulation_steps 1 --prompt_number 150 --loss_every 10 --seed 242 --n_gpu 1 --split_train_file_to_valid --k_train 75 --k_val 75 --k_test 100 --gpu_id 5 --softmax_temperature 20000 --estimator attention --threshold 1.5 --all_dissimilar --add_asc_loss_filtered --asc_temperature 1 --asc_lamb 0.5 --add_hsc_loss --hsc_temperature 1 --hsc_lamb 0.1 --accum_epoch 35",
    ]
    cmd_negative_transfer_order2 = [
        "--name shlpt_dis2_42 --dataset dis_seq2 --task_set dataset_stream --model_set t5-large-lr0.3-256 --train_set train_offline_8_bsz --algo shlpt --load_algo_args --scenario til --epoch 50 --task_num 5 --pri_task shlpt --gradient_accumulation_steps 1 --prompt_number 150 --loss_every 10 --seed 42 --n_gpu 1 --split_train_file_to_valid --k_train 75 --k_val 75 --k_test 100 --gpu_id 5 --softmax_temperature 20000 --estimator attention --threshold 1.5 --all_dissimilar --add_asc_loss_filtered --asc_temperature 1 --asc_lamb 0.5 --add_hsc_loss --hsc_temperature 1 --hsc_lamb 0.1 --accum_epoch 35",
        "--name shlpt_dis2_142 --dataset dis_seq2 --task_set dataset_stream --model_set t5-large-lr0.3-256 --train_set train_offline_8_bsz --algo shlpt --load_algo_args --scenario til --epoch 50 --task_num 5 --pri_task shlpt --gradient_accumulation_steps 1 --prompt_number 150 --loss_every 10 --seed 142 --n_gpu 1 --split_train_file_to_valid --k_train 75 --k_val 75 --k_test 100 --gpu_id 5 --softmax_temperature 20000 --estimator attention --threshold 1.5 --all_dissimilar --add_asc_loss_filtered --asc_temperature 1 --asc_lamb 0.5 --add_hsc_loss --hsc_temperature 1 --hsc_lamb 0.1 --accum_epoch 35",
        "--name shlpt_dis2_242 --dataset dis_seq2 --task_set dataset_stream --model_set t5-large-lr0.3-256 --train_set train_offline_8_bsz --algo shlpt --load_algo_args --scenario til --epoch 50 --task_num 5 --pri_task shlpt --gradient_accumulation_steps 1 --prompt_number 150 --loss_every 10 --seed 242 --n_gpu 1 --split_train_file_to_valid --k_train 75 --k_val 75 --k_test 100 --gpu_id 5 --softmax_temperature 20000 --estimator attention --threshold 1.5 --all_dissimilar --add_asc_loss_filtered --asc_temperature 1 --asc_lamb 0.5 --add_hsc_loss --hsc_temperature 1 --hsc_lamb 0.1 --accum_epoch 35",
    ]
    cmd_negative_transfer_order3 = [
        "--name shlpt_dis3_42 --dataset dis_seq3 --task_set dataset_stream --model_set t5-large-lr0.3-256 --train_set train_offline_8_bsz --algo shlpt --load_algo_args --scenario til --epoch 50 --task_num 5 --pri_task shlpt --gradient_accumulation_steps 1 --prompt_number 150 --loss_every 10 --seed 42 --n_gpu 1 --split_train_file_to_valid --k_train 75 --k_val 75 --k_test 100 --gpu_id 5 --softmax_temperature 20000 --estimator attention --threshold 1.5 --all_dissimilar --add_asc_loss_filtered --asc_temperature 1 --asc_lamb 0.5 --add_hsc_loss --hsc_temperature 1 --hsc_lamb 0.1 --accum_epoch 35",
        "--name shlpt_dis3_142 --dataset dis_seq3 --task_set dataset_stream --model_set t5-large-lr0.3-256 --train_set train_offline_8_bsz --algo shlpt --load_algo_args --scenario til --epoch 50 --task_num 5 --pri_task shlpt --gradient_accumulation_steps 1 --prompt_number 150 --loss_every 10 --seed 142 --n_gpu 1 --split_train_file_to_valid --k_train 75 --k_val 75 --k_test 100 --gpu_id 5 --softmax_temperature 20000 --estimator attention --threshold 1.5 --all_dissimilar --add_asc_loss_filtered --asc_temperature 1 --asc_lamb 0.5 --add_hsc_loss --hsc_temperature 1 --hsc_lamb 0.1 --accum_epoch 35",
        "--name shlpt_dis3_242 --dataset dis_seq3 --task_set dataset_stream --model_set t5-large-lr0.3-256 --train_set train_offline_8_bsz --algo shlpt --load_algo_args --scenario til --epoch 50 --task_num 5 --pri_task shlpt --gradient_accumulation_steps 1 --prompt_number 150 --loss_every 10 --seed 242 --n_gpu 1 --split_train_file_to_valid --k_train 75 --k_val 75 --k_test 100 --gpu_id 5 --softmax_temperature 20000 --estimator attention --threshold 1.5 --all_dissimilar --add_asc_loss_filtered --asc_temperature 1 --asc_lamb 0.5 --add_hsc_loss --hsc_temperature 1 --hsc_lamb 0.1 --accum_epoch 35",
    ]

    batch_run_interactive(cmd_standard_cl_benchmark_order1)
